apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldenapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: goldenapp
  template:
    metadata:
      labels:
        app: goldenapp
    spec:
      containers:
        - name: goldenapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.database.url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.database.password | quote }}



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: goldenapp
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: goldenapp
#   template:
#     metadata:
#       labels:
#         app: goldenapp
#     spec:
#       containers:
#         - name: goldenapp
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - containerPort: {{ .Values.containerPort }}
