apiVersion: v1
kind: Service
metadata:
  name: goldenapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: goldenapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
