apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatapp-pv
  namespace: dev
spec:
  capacity:
    storage: 10Gi  # Adjust the size based on your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Allows a single pod to read/write
  persistentVolumeReclaimPolicy: Retain  # Can be Recycle, Retain, or Delete
  storageClassName: standard
  hostPath:
    path: "/mnt/data/chatapp"  # Path to the storage location on your host machine
