apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql  # Path on the host machine (adjust as needed)
  persistentVolumeReclaimPolicy: Retain
